version: 0.4.{build}
image: Visual Studio 2022

configuration: Release

environment:
  appveyor_sqlconnection: 'Server=.\SQL2017;Database=json;User ID=sa;Password=Password12!'

init:
- ps: $env:nuget_ver=$env:appveyor_build_version
- ps: Update-AppveyorBuild -Version "$env:appveyor_build_version+sha.$($env:appveyor_repo_commit.substring(0,7))"

nuget:
  disable_publish_on_pr: true

services:
  - mssql2017

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(nuget_ver)
  assembly_file_version: $(nuget_ver)
  assembly_informational_version: '{version}'

matrix:
  fast_finish: true # fail fast!

clone_depth: 3  

pull_requests:
  do_not_increment_build_number: true

before_build:
  nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

before_test:
  - ps: .\ci\ps\sql-server-enable-tcp.ps1
  - ps: .\ci\ps\sql-server-create-db.ps1
  - cmd: sqlcmd -S ".\SQL2017" -U "sa" -P "Password12!" -Q "SELECT * FROM information_schema.tables;" -d "json"

test:
  assemblies:
    - '**\*.test.dll'

on_success:
- curl -s -o copilot https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash copilot

deploy:
  provider: NuGet
  api_key:
    secure: bFNGQmfzcl8+qMzGRyjuppyao5/sQlK4w3ikBuYi4qQTniVxdfoyWImJwHHktQm0
  skip_symbols: true
  on:
    branch: master 
