version: 1.0.{build}
image: Visual Studio 2022

configuration: Release

environment:
  appveyor_sqlconnection: 'Server=.\SQL2017;Database=json;User ID=sa;Password=Password12!;TrustServerCertificate=True'

init:
- ps: $env:nuget_ver=$env:appveyor_build_version
- ps: Update-AppveyorBuild -Version "$env:appveyor_build_version+sha.$($env:appveyor_repo_commit.substring(0,7))"


nuget:
  disable_publish_on_pr: true
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '1.0.{build}'
  assembly_version: '1.0.{build}'
  file_version: '1.0.{build}'
  informational_version: '{version}'

services:
  - mssql2017

matrix:
  fast_finish: true # fail fast!

clone_depth: 3  

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: dotnet restore DotJEM.Json.Storage.sln # Restores .NET Standard

build:
  project: DotJEM.Json.Storage.sln
  publish_nuget: true
  publish_nuget_symbols: true

after_build:
  - dotnet pack "DotJEM.Json.Storage\DotJEM.Json.Storage.csproj" --configuration Release --include-symbols --output "C:\Users\appveyor\AppData\Local\Temp\1\97r8s5qo1v" --no-build

before_test:
  - ps: .\ci\ps\sql-server-enable-tcp.ps1
  - ps: .\ci\ps\sql-server-create-db.ps1
  - cmd: sqlcmd -S ".\SQL2017" -U "sa" -P "Password12!" -Q "SELECT * FROM information_schema.tables;" -d "json"

test:
  assemblies:
    - '**\*.test.dll'

on_success:
- curl -s -o copilot https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash copilot

deploy:
  provider: NuGet
  artifact: /**/DotJEM.Json.Storage.nupkg/ 
  api_key:
    secure: L0jKrFMbCq8CU/nA0AluItYUG3KK27qFxCxmEmg2Lc/Js9vyVtNCeABGmr/JG8Dr
  skip_symbols: true
  on:
    branch: master 
