USE [master]
GO
/****** Object:  Database [json]    Script Date: 21-05-2014 16:13:48 ******/
CREATE DATABASE [json]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'json', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.DEV\MSSQL\DATA\json.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'json_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.DEV\MSSQL\DATA\json_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [json] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [json].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [json] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [json] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [json] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [json] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [json] SET ARITHABORT OFF 
GO
ALTER DATABASE [json] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [json] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [json] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [json] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [json] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [json] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [json] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [json] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [json] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [json] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [json] SET  DISABLE_BROKER 
GO
ALTER DATABASE [json] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [json] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [json] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [json] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [json] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [json] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [json] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [json] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [json] SET  MULTI_USER 
GO
ALTER DATABASE [json] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [json] SET DB_CHAINING OFF 
GO
ALTER DATABASE [json] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [json] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [json]
GO
/****** Object:  Table [dbo].[TestArea]    Script Date: 21-05-2014 16:13:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TestArea](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Version] [int] NOT NULL,
	[ContentType] [varchar](256) NOT NULL,
	[Created] [datetime] NOT NULL,
	[Updated] [datetime] NULL,
	[Data] [varbinary](max) NOT NULL,
	[RV] [timestamp] NOT NULL,
 CONSTRAINT [PK_TestArea] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TestAreaHistory]    Script Date: 21-05-2014 16:13:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TestAreaHistory](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Fid] [bigint] NOT NULL,
	[Version] [int] NOT NULL,
	[ContentType] [varchar](256) NOT NULL,
	[Created] [datetime] NOT NULL,
	[Updated] [datetime] NOT NULL,
	[Data] [varbinary](max) NOT NULL,
	[RV] [timestamp] NOT NULL,
 CONSTRAINT [PK_TestAreaHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_TestArea_ContentType]    Script Date: 21-05-2014 16:13:48 ******/
CREATE CLUSTERED INDEX [IX_TestArea_ContentType] ON [dbo].[TestArea]
(
	[ContentType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TestAreaHistory]  WITH NOCHECK ADD  CONSTRAINT [FK_TestAreaHistory_TestArea] FOREIGN KEY([Fid])
REFERENCES [dbo].[TestArea] ([Id])
GO
ALTER TABLE [dbo].[TestAreaHistory] NOCHECK CONSTRAINT [FK_TestAreaHistory_TestArea]
GO
USE [master]
GO
ALTER DATABASE [json] SET  READ_WRITE 
GO
